name: Add Files in Git

on:
  workflow_dispatch:
    
env:
  GitHubMail: "ashwinstr@gmail.com"
  GitHubName: "ashwinstr" 
jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Set Git Configs & Secrets
         run: |
           git config --global user.email ${GitHubMail}
           git config --global user.name ${GitHubName}
           git config --global credential.helper store
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone https://github.com/anonymousx97/ux-termux loop
           cd loop || exit 1
           wget https://partner-images.canonical.com/core/jammy/current/ubuntu-jammy-core-cloudimg-arm64-root.tar.gz
           git add ubuntu-jammy-core-cloudimg-arm64-root.tar.gz
           git commit -m "backup"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/anonymousx97/ux-termux HEAD:main
